[package]
name = "gasless_sol"
version = "0.1.0"
description = "Anchor program for gasless-like escrow transfers"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gasless_sol"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"



